// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5sTL-N2c6g0P0hs5RhbURDvUj79NrDrc',
    appId: '1:531530777011:web:cee80686dfb40a4f8f4bc6',
    messagingSenderId: '531530777011',
    projectId: 'fir-demo-38236',
    authDomain: 'fir-demo-38236.firebaseapp.com',
    storageBucket: 'fir-demo-38236.appspot.com',
    measurementId: 'G-FB7GDRC5QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU_CoGweZCEklRICop8gWoqISldPRBUEk',
    appId: '1:531530777011:android:5e0ccb71ed3c38d98f4bc6',
    messagingSenderId: '531530777011',
    projectId: 'fir-demo-38236',
    storageBucket: 'fir-demo-38236.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV6x2NBbaMMo645-g9fusgU9BrVRduMHQ',
    appId: '1:531530777011:ios:edc4d76b58efcaf18f4bc6',
    messagingSenderId: '531530777011',
    projectId: 'fir-demo-38236',
    storageBucket: 'fir-demo-38236.appspot.com',
    iosClientId: '531530777011-m9rv168q1qoeod6h36kvffsc4tr9gg4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV6x2NBbaMMo645-g9fusgU9BrVRduMHQ',
    appId: '1:531530777011:ios:edc4d76b58efcaf18f4bc6',
    messagingSenderId: '531530777011',
    projectId: 'fir-demo-38236',
    storageBucket: 'fir-demo-38236.appspot.com',
    iosClientId: '531530777011-m9rv168q1qoeod6h36kvffsc4tr9gg4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
